name: one-on-one

on:
  [push]

jobs:
  notes:
    name: create meeting notes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            github.pulls.create({
              owner:'sophshep',
              repo:'one-on-one',
              title:'hello world',
              head:'run-script',
              base:'master',
              body:'ðŸ‘‹ what is up bitches!',
              draft: true
            })
