name: one-on-one

on:
  [push]

jobs:
  notes:
    name: create meeting notes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'hello world',
              head: `new-branch`,
              base: 'master',
              body: 'ðŸ‘‹ what is up bitches!'
            }):
