name: 'Weekly report'
on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * 1

jobs:
  weekly-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout workspace
      uses: actions/checkout@master

    # Get date and store as environment variables
    - name: Get and store variables
      run: |
        echo ::set-env name=BRANCH_NAME::$(date +%F)
        echo ::set-env name=WEEK_OF::"Week of $(date '+%B %d, %Y')"
    
    # Create meeting notes scaffold
    - name: Create weekly notes scaffold file
      run: ./update_notes.sh
        
    # Push changes and set env variable for branch name
    - name: Commit and push notes scaffold to branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
        git config --global user.name $GITHUB_ACTOR
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m "Adds meeting notes scaffold"
        git push --force --set-upstream "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" $BRANCH_NAME
    # Open pull request
    - name: Open pull request for 1:1 notes
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const createPull = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: process.env["WEEK_OF"],
            body: "Commit your 1:1 updates",
            head: process.env["BRANCH_NAME"],
            base: "master",
          });
          github.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: createPull.data.number,
            assignees: [
              "manager-handle",
              "ic-handle"
            ],
          });
